"""empty message

Revision ID: 1ae9ccf8fae6
Revises: None
Create Date: 2016-10-31 00:53:49.973229

"""

# revision identifiers, used by Alembic.
revision = '1ae9ccf8fae6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_books_book_name'), 'books', ['book_name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_book_name'), table_name='books')
    ### end Alembic commands ###
