"""empty message

Revision ID: 9026d7521ce0
Revises: 1ae9ccf8fae6
Create Date: 2016-11-01 00:23:24.590328

"""

# revision identifiers, used by Alembic.
revision = '9026d7521ce0'
down_revision = '1ae9ccf8fae6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
